# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number(xcodeproj: "emurgo.xcodeproj")
    build_app(workspace: "emurgo.xcworkspace", scheme: "emurgo")
    upload_to_testflight(skip_submission: true)
  end

  desc "Builds the project. Useful to verify a succesful compilation."
  lane :build do
    get_certificates()           # invokes cert
    get_provisioning_profile(provisioning_name: "com.emurgo.yoroi AppStore", cert_id: "HPC5U2RRJZ")   # invokes sigh
    build_app(
      workspace: "emurgo.xcworkspace", 
      scheme: "emurgo", 
      export_options: {
        "provisioningProfiles": {
          "com.emurgo.yoroi": "com.emurgo.yoroi AppStore"
        },
        "method": "app-store",
        "signingStyle": "manual"
      }
    )
  end

  desc "Builds the project. Useful to verify a succesful compilation."
  lane :bitrise_build do
    get_certificates()           # invokes cert
    get_provisioning_profile(provisioning_name: "com.emurgo.yoroi AppStore", cert_id: "HPC5U2RRJZ")   # invokes sigh
    build_app(
      workspace: "emurgo.xcworkspace", 
      scheme: "emurgo", 
      export_options: {
        "provisioningProfiles": {
          "com.emurgo.yoroi": "com.emurgo.yoroi AppStore"
        },
        "method": "app-store",
        "signingStyle": "manual"
      }
    )
  end
end